title: Kristina Schogoleva # your name (or website title) here
logo: "images/photo_main_port.png" # your photo (or logo) here
description: >
  Data Analyst with a background in Mathematics and Computer Science, focused on statistics, experimentation, and product analytics.

  Trained through self-study and the Generation data analytics program, with experience in SQL, Python, data visualization, and A/B testing.

  Interested in applying statistical methods to product decision-making and experimentation design.  <br><br>
 
  <a href="www.linkedin.com/in/kristina-sсhogoleva95">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
