title: Kristina Schogoleva # your name (or website title) here
logo: "images/photo_main_port.png" # your photo (or logo) here
description: >
  <h2 style="margin-bottom: 10px;">Data Analyst</h2>

  <p>Background in Mathematics and Computer Science with a focus on statistics, experimentation, and product analytics.</p>

  <p>Completed the Generation UK & Ireland Data Analytics program.</p>

  <p>Interested in A/B testing, product experimentation, and data-driven decision-making.</p>

  <p style="margin-top: 15px;">
     <a href="https://www.linkedin.com/in/kristina-sсhogoleva95">LinkedIn</a>
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
github_username: ""
show_downloads: false
